python make_aQGC_plots.py -n ../WWAnalysisRun2/OutPutRootFile_VBFsel1.root  --grid -v AK4_DR_GENRECO_11 AK4_DR_GENRECO_12 AK4_DR_GENRECO_21 AK4_DR_GENRECO_22  --leg "DR(led - led)" "DR(led - SubLed)" "DR(SubLed - Led)" "DR(SubLed - SubLed)" --xmin 0 --xmax 10 --xlabel "#Delta R(GEN-RECO)" --cut "vbf_maxpt_jj_Deta<1.0" -o VBFsel1_GEN_RECO_DR.png --legPos "tr"
#python make_aQGC_plots.py -n ../WWAnalysisRun2/OutPutRootFile_VBFsel2.root  --grid -v AK4_DR_GENRECO_11 AK4_DR_GENRECO_12 AK4_DR_GENRECO_21 AK4_DR_GENRECO_22  --leg "DR(led - led)" "DR(led - SubLed)" "DR(SubLed - Led)" "DR(SubLed - SubLed)" --xmin 0 --xmax 10 --xlabel "#Delta R(GEN-RECO)" --cut "vbf_maxpt_jj_Deta<1.0" -o VBFsel2_GEN_RECO_DR.png --legPos "tr"
#python make_aQGC_plots.py -n ../WWAnalysisRun2/OutPutRootFile_VBFsel3.root  --grid -v AK4_DR_GENRECO_11 AK4_DR_GENRECO_12 AK4_DR_GENRECO_21 AK4_DR_GENRECO_22  --leg "DR(led - led)" "DR(led - SubLed)" "DR(SubLed - Led)" "DR(SubLed - SubLed)" --xmin 0 --xmax 10 --xlabel "#Delta R(GEN-RECO)" --cut "vbf_maxpt_jj_Deta<1.0" -o VBFsel3_GEN_RECO_DR.png --legPos "tr"
#python make_aQGC_plots.py -n ../WWAnalysisRun2/OutPutRootFile_VBFsel2.root  --grid -v AK4_1_pt_gen vbf_maxpt_j1_pt  --leg "GEN" "RECO"  --xmin 0 --xmax 1000 --xlabel "Leading VBF jet p_{T}"  -o GEN_RECO_VBF_Leading_JetPt.png --legPos "tr" 
#python make_aQGC_plots.py -n ../WWAnalysisRun2/OutPutRootFile_VBFsel2.root  --grid -v AK4_2_pt_gen vbf_maxpt_j2_pt  --leg "GEN" "RECO"  --xmin 0 --xmax 1000 --xlabel "Sub-Leading VBF jet p_{T}" -o GEN_RECO_VBF_SubLeading_JetPt.png --legPos "tr" 
#python make_aQGC_plots.py -n ../WWAnalysisRun2/OutPutRootFile_VBFsel2.root  --grid -v AK4_1_eta_gen vbf_maxpt_j1_eta  --leg "GEN" "RECO"  --xmin -5 --xmax 5 --xlabel "Leading VBF jet #eta"  -o GEN_RECO_VBF_Leading_Jeteta.png --legPos "tr"
#python make_aQGC_plots.py -n ../WWAnalysisRun2/OutPutRootFile_VBFsel2.root  --grid -v AK4_2_eta_gen vbf_maxpt_j2_eta  --leg "GEN" "RECO"  --xmin -5 --xmax 5 --xlabel "Sub-Leading VBF jet #eta" -o GEN_RECO_VBF_SubLeading_Jeteta.png --legPos "tr" 

#python make_aQGC_plots.py -n ../WWAnalysisRun2/OutPutRootFile_VBFsel1.root ../WWAnalysisRun2/OutPutRootFile_VBFsel2.root ../WWAnalysisRun2/OutPutRootFile_VBFsel3.root --grid -v vbf_maxpt_j1_eta -o VBF_leading_eta.png --leg "Highest (p_{T}1+p_{T}2)" "Highest m_{jj}" "Highest #Delta #eta_{jj}" --xmin -5 --xmax 5 --xlabel "VBF leading jet #eta" --cut "vbf_maxpt_jj_Deta<1.0" 
#python make_aQGC_plots.py -n ../WWAnalysisRun2/OutPutRootFile_VBFsel1.root ../WWAnalysisRun2/OutPutRootFile_VBFsel2.root ../WWAnalysisRun2/OutPutRootFile_VBFsel3.root --grid -v vbf_maxpt_j2_eta -o VBF_Subleading_eta.png --leg "Highest (p_{T}1+p_{T}2)" "Highest m_{jj}" "Highest #Delta #eta_{jj}" --xmin -5 --xmax 5 --xlabel "VBF Sub-leading jet #eta" --cut "vbf_maxpt_jj_Deta<1.0" 
#python make_aQGC_plots.py -n ../WWAnalysisRun2/OutPutRootFile_VBFsel1.root ../WWAnalysisRun2/OutPutRootFile_VBFsel2.root ../WWAnalysisRun2/OutPutRootFile_VBFsel3.root --grid -v vbf_maxpt_jj_Deta -o VBF_Deltaeta.png --leg "Highest (p_{T}1+p_{T}2)" "Highest m_{jj}" "Highest #Delta #eta_{jj}" --xmin 0 --xmax 5 --xlabel "VBF #Delta #eta" --cut "vbf_maxpt_jj_Deta<1.0"  --legPos "tr"
#
#python make_aQGC_plots.py -n ../WWAnalysisRun2/OutPutRootFile_VBFsel1.root ../WWAnalysisRun2/OutPutRootFile_VBFsel2.root ../WWAnalysisRun2/OutPutRootFile_VBFsel3.root --grid -v vbf_maxpt_jj_m -o VBF_mjj.png --leg "Highest (p_{T}1+p_{T}2)" "Highest m_{jj}" "Highest #Delta #eta_{jj}" --xmin 0 --xmax 600 --xlabel "VBF m_{jj}" --cut "vbf_maxpt_jj_Deta<1.0" --legPos "tr"
