#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root --grid -v AK4_DR_GENRECO_11 AK4_DR_GENRECO_12 AK4_DR_GENRECO_21 AK4_DR_GENRECO_22 --leg "DR(Led-Led)" "DR(Led-SubLed)" "DR(SubLed-Led)" "DR(SubLed - SubLed)" --xmin 0 --xmax 10 --xlabel "#Delta R(GEN-RECO)"  -o VBFsel1_GEN_RECO_DR_Ele.png --legPos "tl"  --nbin 10
##--cut "AK4_DR_GENRECO_11>1 && AK4_DR_GENRECO_12>1 && AK4_DR_GENRECO_22 > 1 && AK4_DR_GENRECO_21>1"
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v "abs(AK4_1_pt_gen-vbf_maxpt_j1_pt)/(AK4_1_pt_gen+vbf_maxpt_j1_pt)"  "abs(AK4_2_pt_gen-vbf_maxpt_j2_pt)/(AK4_2_pt_gen+vbf_maxpt_j2_pt)" --leg "Leading jet" "Sub-Leading jet"   --xmin 0 --xmax 1 --xlabel "|p_{T}(Gen)-p_{T}(reco)|/(p_{T}(Gen)+p_{T}(reco))"  -o GEN_RECO_VBF_diffGENRECO_JetPt_Ele.png --legPos "tl"  
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v "abs(AK4_1_eta_gen-vbf_maxpt_j1_eta)/(AK4_1_eta_gen+vbf_maxpt_j1_eta)"  "abs(AK4_2_eta_gen-vbf_maxpt_j2_eta)/(AK4_2_eta_gen+vbf_maxpt_j2_eta)" --leg "Leading jet" "Sub-Leading jet"   --xmin 0 --xmax 1 --xlabel "|#eta (Gen)-#eta (reco)|/(#eta (Gen)+#eta (reco))"  -o GEN_RECO_VBF_diffGENRECO_Jeteta_Ele.png --legPos "tl"  
#
############# Leptons	#########################################################
#
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v lep_pt_gen l_pt1  --leg "GEN" "RECO"  --xmin 30 --xmax 700 --xlabel "Lepton p_{T}"  -o GEN_RECO_Leptons_pt_Ele.png --legPos "tl"  --nbin 10
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v lep_eta_gen l_eta1  --leg "GEN" "RECO"  --xmin -2.5 --xmax 2.5 --xlabel "Lepton #eta"  -o GEN_RECO_Leptons_eta_Ele.png --legPos "tl"  --nbin 10
python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v WW_mass_gen mass_lvj_type0 mass_lvj_type2 mass_lvj_run2  --leg "GEN" "RECO (type0)" "RECO (type2)" "RECO (run2)" --xmin 0 --xmax 2500 --xlabel "mWW invariant mass"  -o mWW_mass.png --legPos "tl"  --nbin 20 --cut "(type==1) && (l_pt2<0) && (PuppiAK8_jet_tau2tau1<0.55) && ((PuppiAK8_jet_mass_so>50)&&(PuppiAK8_jet_mass_so<110)) && (pfMETpuppi>30) && (pfMET>30) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>2.5)"
python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v lepW_m_gen v_puppi_mass_type2 v_puppi_mass_type0 v_puppi_mass_run2   --leg "GEN" "RECO (type2)" "RECO (type0)" "RECO (run2)"  --xmin 0 --xmax 400 --xlabel "W(lep) mass"  -o mW_lep_mass.png --legPos "tl"  --nbin 20 --cut "(type==1) && (l_pt2<0) && (PuppiAK8_jet_tau2tau1<0.55) && ((PuppiAK8_jet_mass_so>50)&&(PuppiAK8_jet_mass_so<110)) && (pfMETpuppi>30) && (pfMET>30) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>2.5)"
python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v lepW_m_gen v_mass_type2 v_mass_type0 v_mass_run2   --leg "GEN" "RECO (type2)" "RECO (type0)" "RECO (run2)"  --xmin 0 --xmax 400 --xlabel "W(lep) mass puppi"  -o mW_lep_mass_puppi.png --legPos "tl"  --nbin 20 --cut "(type==1) && (l_pt2<0) && (PuppiAK8_jet_tau2tau1<0.55) && ((PuppiAK8_jet_mass_so>50)&&(PuppiAK8_jet_mass_so<110)) && (pfMETpuppi>30) && (pfMET>30) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>2.5)"
python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v  lepW_pt_gen v_pt_type2 v_pt_type0 v_pt_run2  --leg "GEN" "RECO (type2)" "RECO (type0)" "RECO (run2)"  --xmin 0 --xmax 500 --xlabel "W(lep) p_{T}"  -o W_lep_pT.png --legPos "tl"  --nbin 20 --cut "(type==1) && (l_pt2<0) && (PuppiAK8_jet_tau2tau1<0.55) && ((PuppiAK8_jet_mass_so>50)&&(PuppiAK8_jet_mass_so<110)) && (pfMETpuppi>30) && (pfMET>30) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>2.5)"
python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v lepW_eta_gen v_eta_type2 v_eta_type0 v_eta_run2  --leg "GEN" "RECO (type2)" "RECO (type0)" "RECO (run2)"  --xmin -2.5 --xmax 2.5 --xlabel "W(lep) #eta"  -o W_lep_eta.png --legPos "tl"  --nbin 20 --cut "(type==1) && (l_pt2<0) && (PuppiAK8_jet_tau2tau1<0.55) && ((PuppiAK8_jet_mass_so>50)&&(PuppiAK8_jet_mass_so<110)) && (pfMETpuppi>30) && (pfMET>30) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>2.5)"
python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v  nu_pz_gen nu_pz_type2 nu_pz_type0 nu_pz_run2  --leg "GEN" "RECO (type2)" "RECO (type0)" "RECO (run2)"   --xmin -500 --xmax 500 --xlabel "MET p_{z}"  -o MET_pZ.png --legPos "tl"  --nbin 20 --cut "(type==1) && (l_pt2<0) && (PuppiAK8_jet_tau2tau1<0.55) && ((PuppiAK8_jet_mass_so>50)&&(PuppiAK8_jet_mass_so<110)) && (pfMETpuppi>30) && (pfMET>30) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>2.5)"
python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v  v_puppi_mt_type2 v_puppi_mt_type0 v_puppi_mt_run2  --leg "RECO (type2)" "RECO (type0)" "RECO (run2)"  --xmin 0 --xmax 700 --xlabel "mT (W)"  -o mT_W.png --legPos "tl"  --nbin 20 --cut "(type==1) && (l_pt2<0) && (PuppiAK8_jet_tau2tau1<0.55) && ((PuppiAK8_jet_mass_so>50)&&(PuppiAK8_jet_mass_so<110)) && (pfMETpuppi>30) && (pfMET>30) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>2.5)"
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v    --leg "GEN" "RECO"  --xmin -2.5 --xmax 2.5 --xlabel ""  -o .png --legPos "tl"  --nbin 10
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v    --leg "GEN" "RECO"  --xmin -2.5 --xmax 2.5 --xlabel ""  -o .png --legPos "tl"  --nbin 10
##
############## VBF jets	#########################################################
##
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_1_pt_gen vbf_maxpt_j1_pt  --leg "GEN" "RECO"  --xmin 30 --xmax 700 --xlabel "Leading VBF jet p_{T}"  -o GEN_RECO_VBF_Leading_JetPt_Ele.png --legPos "tl"  --nbin 10
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_2_pt_gen vbf_maxpt_j2_pt  --leg "GEN" "RECO"  --xmin 30 --xmax 450 --xlabel "Sub-Leading VBF jet p_{T}" -o GEN_RECO_VBF_SubLeading_JetPt_Ele.png --legPos "tl" --nbin 10
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_1_eta_gen vbf_maxpt_j1_eta  --leg "GEN" "RECO"  --xmin -5 --xmax 5 --xlabel "Leading VBF jet #eta"  -o GEN_RECO_VBF_Leading_Jeteta_Ele.png --legPos "tl" --nbin 10 
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_2_eta_gen vbf_maxpt_j2_eta  --leg "GEN" "RECO"  --xmin -5 --xmax 5 --xlabel "Sub-Leading VBF jet #eta" -o GEN_RECO_VBF_SubLeading_Jeteta_Ele.png --legPos "tl"  --nbin 10
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_jj_DeltaEta_gen vbf_maxpt_jj_Deta  --leg "GEN" "RECO"  --xmin 2 --xmax 10 --xlabel "VBF jet #Delta #eta" -o GEN_RECO_VBF_Jet_Deltaeta_Ele.png --legPos "tl" --nbin 8 
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_jj_mass_gen vbf_maxpt_jj_m  --leg "GEN" "RECO"  --xmin 0 --xmax 3000 --xlabel "m_{jj} (VBF)" -o GEN_RECO_VBF_Jet_InvMass_Ele.png --legPos "tl"  --nbin 6
##
###############	W-jets related variables	###########################
##
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v hadW_pt_gen ungroomed_PuppiAK8_jet_pt  --leg "GEN" "RECO"  --xmin 200 --xmax 1200 --xlabel "Hadronic W pT" -o GEN_RECO_AK8_pT_Ele.png --legPos "tl"   --nbin 10
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v hadW_eta_gen ungroomed_PuppiAK8_jet_eta  --leg "GEN" "RECO"  --xmin -3 --xmax 3 --xlabel "Hadronic W #eta" -o GEN_RECO_AK8_eta_Ele.png --legPos "tl"  
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v hadW_phi_gen ungroomed_PuppiAK8_jet_phi  --leg "GEN" "RECO"  --xmin -3 --xmax 3 --xlabel "Hadronic W #phi" -o GEN_RECO_AK8_phi_Ele.png --legPos "tl"   
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v hadW_m_gen AK8jet_mass_pr AK8jet_mass_so AK8jet_mass_tr  --leg "GEN" "RECO (Prunned)" "RECO (Softdrop)" "RECO (trimmed)" --xmin 0 --xmax 150 --xlabel "W-jet Invariant Mass" -o GEN_RECO_AK8_mass_Ele.png --legPos "tl" 
#python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v WW_mass_gen mass_lvj_type2_PuppiAK8  --leg "GEN" "RECO" --xmin 500 --xmax 1500 --xlabel "WW Invariant Mass" -o GEN_RECO_WW_Ele.png --legPos "tl" --nbin 10
#
#
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root --grid -v AK4_DR_GENRECO_22 AK4_DR_GENRECO_11  --leg "DR(SubLed - SubLed)" "DR(Led - Led)" --xmin 0 --xmax 10 --xlabel "#Delta R(GEN-RECO)"  -o VBFsel1_GEN_RECO_DR_Mu.png --legPos "tc"
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v "abs(AK4_1_pt_gen-vbf_maxpt_j1_pt)/(AK4_1_pt_gen+vbf_maxpt_j1_pt)"  "abs(AK4_2_pt_gen-vbf_maxpt_j2_pt)/(AK4_2_pt_gen+vbf_maxpt_j2_pt)" --leg "Leading jet" "Sub-Leading jet"  --nbin 20 --xmin 0 --xmax 1 --xlabel "|p_{T}(Gen)-p_{T}(reco)|/(p_{T}(Gen)+p_{T}(reco))"  -o GEN_RECO_VBF_diffGENRECO_JetPt_mu.png --legPos "tl" 
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v "abs(AK4_1_eta_gen-vbf_maxpt_j1_eta)/(AK4_1_eta_gen+vbf_maxpt_j1_eta)"  "abs(AK4_2_eta_gen-vbf_maxpt_j2_eta)/(AK4_2_eta_gen+vbf_maxpt_j2_eta)" --leg "Leading jet" "Sub-Leading jet"  --nbin 20 --xmin 0 --xmax 1 --xlabel "|#eta (Gen)-#eta (reco)|/(#eta (Gen)+#eta (reco))"  -o GEN_RECO_VBF_diffGENRECO_Jeteta_mu.png --legPos "tl" 
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_1_pt_gen vbf_maxpt_j1_pt  --leg "GEN" "RECO"  --xmin 0 --xmax 1000 --xlabel "Leading VBF jet p_{T}"  -o GEN_RECO_VBF_Leading_JetPt_Mu.png --legPos "tl" 
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_2_pt_gen vbf_maxpt_j2_pt  --leg "GEN" "RECO"  --xmin 0 --xmax 1000 --xlabel "Sub-Leading VBF jet p_{T}" -o GEN_RECO_VBF_SubLeading_JetPt_Mu.png --legPos "tl" 
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_1_eta_gen vbf_maxpt_j1_eta  --leg "GEN" "RECO"  --xmin -5 --xmax 6 --xlabel "Leading VBF jet #eta"  -o GEN_RECO_VBF_Leading_Jeteta_Mu.png --legPos "tl"
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_2_eta_gen vbf_maxpt_j2_eta  --leg "GEN" "RECO"  --xmin -5 --xmax 6 --xlabel "Sub-Leading VBF jet #eta" -o GEN_RECO_VBF_SubLeading_Jeteta_Mu.png --legPos "tl" 
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_jj_DeltaEta_gen vbf_maxpt_jj_Deta  --leg "GEN" "RECO"  --xmin 0 --xmax 10 --xlabel "VBF jet #Delta #eta" -o GEN_RECO_VBF_Jet_Deltaeta_Mu.png --legPos "tl" 
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v AK4_jj_mass_gen vbf_maxpt_jj_m  --leg "GEN" "RECO"  --xmin 0 --xmax 3000 --xlabel "m_{jj} (VBF)" -o GEN_RECO_VBF_Jet_InvMass_Mu.png --legPos "tl" 
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v hadW_pt_gen ungroomed_PuppiAK8_jet_pt  --leg "GEN" "RECO"  --xmin 0 --xmax 1500 --xlabel "Hadronic W pT" -o GEN_RECO_AK8_pT_Mu.png --legPos "tl" 
##
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v hadW_m_gen AK8jet_mass_pr AK8jet_mass_so AK8jet_mass_tr  --leg "GEN" "RECO (Prunned)" "RECO (Softdrop)" "RECO (trimmed)" --xmin 0 --xmax 150 --xlabel "W-jet Invariant Mass" -o GEN_RECO_AK8_mass_Mu.png --legPos "tl" --nbin 15
##python make_aQGC_plots.py -n /afs/cern.ch/user/r/rasharma/work/public/aQGC_Ntuples/OutPut_Ele_6Sep/Signal_WpWm_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_EleMu.root  --grid -v WW_mass_gen mass_lvj_type2_PuppiAK8  --leg "GEN" "RECO" --xmin 0 --xmax 1500 --xlabel "WW Invariant Mass" -o GEN_RECO_WW_mu.png --legPos "tl" --nbin 15
